<h1> Hafta 1: Python ve Qiskit'e Giriş<h1>

Python nesne yönelimli, modüler ve etkileşimli bir dildir. Python hakkında temel bilginizin olduğunu varsayıp belli kısımları tekrar edeceğiz. Fonksiyon ve sınıf tanımlamayla başlayacağız çünkü Qiskit aslında kendi kodumuzda kullanacağımız bir sınıftır.


##Fonksiyon ve Sınıf

**<h3>Fonksiyon tanımlama:<h3>**

In [ ]:
x=3
#define kelimesinin kısaltması olan "def"le tanımlanır.
def fonksiyon():
  y=x+5
  print(y)

#fonksiyona verdiğiniz isimle çağırılır.
fonksiyon()

Fonksiyonlar basitçe bu şekilde tanımlanır. Bunun yanında bir fonksiyona parametreler ekleyerek fonksiyonu farklı değişkenler ve durumlar için de tanımlayabilriz.

Örnek:

In [ ]:
"""Aynı fonksiyonun içine a parametresini tanımlayıp istediğimiz sayıya 5 ekleyebileceğiz"""
def fonksiyon(a):
  a+=5
  print(a)
fonksiyon(3)

**<h3>Class:<h3>**

Class tanımlamak da fonksiyon tanımlamaya benzer fakat classlar obje ve bu objelere fonksiyonlar tanımlamak için kullanılır.

In [ ]:
class Hayvan:
#__init__ fonksiyonu tanımlanan class'ın varsayılan fonksiyonudur.
  def __init__(self, isim, tur):
    #bu objelere self. komutuyla değişkenler atanır.
    self.isim = isim
    self.tur = tur
#class çağırıldığında beraberinde varsayılan fonksiyonun parametreleriyle birlikte çağırılır
hayvan1 = Hayvan("Karabaş", "Golden")

#objeye tanımlanan değişkenler aşağıdaki şekilde çağırılır.
print(hayvan1.isim)
print(hayvan1.tur)

**<h3> Ödev-1<h3>**

Aşağıda verilen kondisyonları sağlayan bir sınıf tanımlayın.


*   Sınıfın adı Öğrenci olacaktır.
*   Öğrencinin **ismi, sınıfı ve ödev sayısı** her obje için tanımlanacaktır.
*   Sınıfın içinde tanımlanan bir **fonksiyon** öğrencinin ödevlerini eksiltecektir.

Sonrasında tanımlanan sınıfla bir obje oluşturulup *ödevleri bitene kadar*(döngü) ödevleri eksilten fonksiyon çağıralacaktır. Her ödev eksiltme fonksiyonunda kaç ödev kaldığı da yazdırılacaktır.






---
!!!Ödevle alakalı bir sıkıntı yaşarsanız veya ödevi bitirip kontrol etmek isterseniz Whatsapp üzerinden bizimle iletişime geçebilirsiniz.


In [ ]:
#Kodunuzu buraya yazabilirsiniz.

# math Kütüphanesi

Python kendi kaynak kodları haricinde bu kodlarla oluşturulmuş pek çok özelliğe sahip ve bu özellikler kütüphane olarak adlandırıyorlar. Kütüphaneler aslında birer class'lardır. Bunları kendi projenizde kullanmak istediğinizde kodunuza aktarmanız gerekiyor. Biz math kütüphanesiyle başlayacağımızdan onu tanımlıyoruz.


**Örnek:**
```python
from math import sin, pi
//math burada kullandığımız kütüphaneyi temsil ediyor
/*sin ve pi yse bu kütüphaneden kendi kodunuza taşıdığınız fonksiyon ve değişkenleri temsil ediyor*/
```


#Karmaşık Sayılar

Karmaşık sayıların kaynağı aşağıdaki i sayısıdır(pdf'de de bahsetmiştik zaten.).

 $$\sqrt{-1}=i$$

Karmaşık sayılar iki kısıma ayrılır ve o şekilde gösterilir. Bir reel ve bir de karmaşık kısımdan oluşur.

$$z=a+bi$$

<img src="https://gitlab.com/qworld/qeducation/qbook101/raw/main/qbook101/images/ch1/Complex_number.svg" width="250" align="center">
<p style="font-size:10px;font-style:italic;text-align:right">
<a href="https://en.wikipedia.org/wiki/Complex_number#/media/File:Complex_number_illustration_modarg.svg" target="_blank">source of image</a> (license CC BY-SA 3.0)</p>

Bu iki kısmı da yukarıda gördüğünüz gibi koordinat sistemi üzerinde gösterebiliriz. Python'da da complex(i,j) fonksiyonuyla tanımlanır. i reel kısım, j ise karmaşık kısmı temsil eder.

In [ ]:
def cnumbercreator(i,j):
  a=complex(i,j)
  print(a)
  print(a.real)
  print(a.imag)
cnumbercreator(3,5)

Karmaşık sayıların çok bahsedeceğimiz bir özelliği de eşlenik özelliğidir. Bir karmaşık sayının kendi eşleniği ile çarpımı reel bir sonuç verir. complex(i, j) ile tanımladığımız karmaşık sayının eşleniğini .conjugate() fonksiyonuyla alıyoruz.

In [ ]:
def cnumbercreator(i,j):
  a=complex(i,j)
  print(a)
  print(a.conjugate())
cnumbercreator(5,4)

# numpy, Vektör ve Matrisler

In [ ]:
import numpy as np

Şimdi, numpy'da nasıl vektör oluşturulur onu göreceğiz. Numpy, python dili için oluşturulan bir bilimsel hesap kütüphanesidir.
Numpy'daki olanaklar fazladır, biz sadece birkaçını göstereceğiz.

Öncelikle $v = \begin{pmatrix} 3 \\ 6 \\ 7 \end{pmatrix}$ vektörünü ve $M = \begin{pmatrix} 1 & 3 & 7 \\ 2 & 6 & 5 \\ 2 & 7 & 0\end{pmatrix}$ matrisini tanımlayalım.


In [ ]:
v = np.array([3,6,7])
M = np.array([[1,3,7],[2,6,5],[2,7,0]])

In [ ]:
print(v)

In [ ]:
print(M)

Şimdi, numpy'da iç çarpımın ve matris çarpımının nasıl yapıldığını görelim. Alışkanlık olsun diye buraya sonuçları yazıyoruz:

$v \cdot v = \begin{pmatrix}3 \\ 6 \\ 7\end{pmatrix}\begin{pmatrix}3 \\ 6 \\ 7\end{pmatrix} = \begin{pmatrix}3 & 6 & 7\end{pmatrix}\begin{pmatrix}3 \\ 6 \\ 7\end{pmatrix} = 9 + 36 + 49 = 94$

$M \cdot v = \begin{pmatrix} 1 & 3 & 7 \\ 2 & 6 & 5 \\ 2 & 7 & 0\end{pmatrix} \begin{pmatrix}3 \\ 6 \\ 7\end{pmatrix} = \begin{pmatrix}3 + 18 + 49 \\ 6 + 36 + 35 \\ 6 + 42 + 0\end{pmatrix} = \begin{pmatrix}70 \\ 77 \\ 48\end{pmatrix}$

Eğer pratik yapmak istiyorsanız bu işlemleri kendiniz de yapmanızı öneririz.
numpy'da çarpım için np.dot fonksiyonu kullanılıyor. np.dot fonksiyonunun ilk parametresi çarpılacak ilk nesneyi, ikinci parametresi ise ikincisini verir. Ayrıca bir satır vektörüyle bir sütun vektörünü girmeniz aynı vektörlerin ikisinin de sütun hâlini girmenizle aynı sonucu verir.

In [ ]:
vdotv = np.dot(v,v)
print(vdotv)

In [ ]:
vsutun = np.array([[i] for i in v])
print(vsutun)

In [ ]:
vdotvs = np.dot(v,vsutun)
print(vdotvs)

In [ ]:
mdotv = np.dot(M,v)
print(mdotv)

In [ ]:
mdotm = np.dot(M,M)
print(mdotm)

Şimdi ikinci bir matris tanımlayalım. Bu matris, $A = \begin{pmatrix} 2 & 4 & 3 \\ 2 & 0 & 1 \\ 4 & 3 & 0\end{pmatrix}$ olsun. Bu sefer $A\cdot M$'yi bulmayı size bırakıyoruz.

In [ ]:
A = np.array([[2,4,3],[2,0,1],[4,3,0]])
mdota = np.dot(M,A)
print(mdota)

[[36 25  6]
 [36 23 12]
 [18  8 13]]


In [ ]:
adotm = np.dot(A,M)
print(adotm)

Gördüğünüz üzere, matris çarpımının sırasını değiştirince sonuç aynı olmuyor. Matematiksel olarak, genel durumda $AM \neq MA$. Bunu şu şekilde görmek en kolaydır:
$A$'nın ve $M$'nin ilk satır vektörleri $a,m$, $A$'nın ve $M$'nin ilk sütun vektörü $a',m'$ olsun. O zaman $AM$ matrisinin ilk girdisi $a\cdot m'$ iken $MA$ matrisinin ilk girdisi $m \cdot a'$'dır. Bu iki iç çarpım genel durumda eşit değildir. Biraz daha örnek görelim:

In [ ]:
M1 = np.array([[1,5,3],[2,7,4],[9,1,3]])
M2 = np.array([[3,5,2],[1,5,3],[2,3,5]])
M3 = np.array([[1,2,3],[0,2,0],[4,2,1]])

In [ ]:
M1M2 = np.dot(M1,M2)
M2M1 = np.dot(M2,M1)
print(M1M2)
print(M2M1)

In [ ]:
M1M3 = np.dot(M1,M3)
M3M1 = np.dot(M3,M1)
print(M1M3)
print(M3M1)



---



Bu durumda $AM$ ve $MA$ arasındaki farkı fizik dünyası (ve matematik) için ilgi çekicidir. Temelde, kuantum operatörler için bu farkın 0 olması ölçülen iki özelliğin birbirini etkilemediğini gösterir. Heisenberg belirsizlik ilkesinden bildiğimiz üzere momentum ve pozisyon operatörleri için bu fark kesinlikle 0 değildir. Bu farkı, $[A,M] = AM - MA$ olarak gösterebiliriz.



---

